repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
    - id: markdownlint 

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.20.0
  hooks:
  - id: eslint
    args: ['--max-warnings=0', '--fix']
    additional_dependencies:
      - eslint@7.8.1
      - eslint-plugin-vue@6.2.2
    files: \.(js|vue)$
    types: [file]
